# Generated by Django 5.0.4 on 2024-05-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
