# Generated by Django 5.0.4 on 2024-05-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_friendsetting_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('Pagrindinis', 'Pagrindinis'), ('Vidurinis', 'Vidurinis'), ('Aukštasis', 'Aukstasis'), ('Aukštesnysis', 'Aukstesnysis'), ('Pradinis', 'Pradinis')], max_length=15, null=True),
        ),
    ]
