# Generated by Django 5.0.4 on 2024-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_user_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest_color_four',
            field=models.CharField(choices=[('#D9D9D9', 'Gray'), ('#F6C4C4', 'Red'), ('#B2D8EE', 'Blue'), ('#B8F2C1', 'Green'), ('#F1B8F2', 'Purple'), ('#F6EAA5', 'Yellow')], default='#D9D9D9', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_color_one',
            field=models.CharField(choices=[('#D9D9D9', 'Gray'), ('#F6C4C4', 'Red'), ('#B2D8EE', 'Blue'), ('#B8F2C1', 'Green'), ('#F1B8F2', 'Purple'), ('#F6EAA5', 'Yellow')], default='#D9D9D9', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_color_three',
            field=models.CharField(choices=[('#D9D9D9', 'Gray'), ('#F6C4C4', 'Red'), ('#B2D8EE', 'Blue'), ('#B8F2C1', 'Green'), ('#F1B8F2', 'Purple'), ('#F6EAA5', 'Yellow')], default='#D9D9D9', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_color_two',
            field=models.CharField(choices=[('#D9D9D9', 'Gray'), ('#F6C4C4', 'Red'), ('#B2D8EE', 'Blue'), ('#B8F2C1', 'Green'), ('#F1B8F2', 'Purple'), ('#F6EAA5', 'Yellow')], default='#D9D9D9', max_length=7),
        ),
    ]
