# Generated by Django 5.0.4 on 2024-05-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Vyras', 'Vyras'), ('Moteris', 'Moteris')], max_length=10, null=True),
        ),
    ]
