# Generated by Django 5.0.4 on 2024-05-18 20:34

import antivienas.database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_user_interest_color_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_one',
            field=models.ImageField(blank=True, default='static/assets/user-no-avatar.png', null=True, upload_to=antivienas.database.models.user_img_upload_path),
        ),
    ]
