# Generated by Django 5.0.4 on 2024-11-12 21:01

import antivienas.database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_user_default_img_alter_order_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=5953),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_one',
            field=models.ImageField(blank=True, null=True, storage=antivienas.database.models.OverwriteStorage(), upload_to=antivienas.database.models.user_img_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_three',
            field=models.ImageField(blank=True, null=True, storage=antivienas.database.models.OverwriteStorage(), upload_to=antivienas.database.models.user_img_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_two',
            field=models.ImageField(blank=True, null=True, storage=antivienas.database.models.OverwriteStorage(), upload_to=antivienas.database.models.user_img_upload_path),
        ),
    ]
