# Generated by Django 5.0.4 on 2024-11-15 13:05

import antivienas.database.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_order_confirmation_code_alter_user_img_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_three',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_two',
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=7587),
        ),
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=antivienas.database.models.user_img_upload_path)),
                ('is_avatar', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
