# Generated by Django 5.0.4 on 2024-11-16 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_user_default_img_remove_user_img_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsetting',
            name='friend',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='friend', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=2919),
        ),
    ]
