# Generated by Django 5.0.4 on 2024-11-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_friendsetting_friend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=5075),
        ),
    ]
