# Generated by Django 5.0.4 on 2024-11-19 21:00

import antivienas.database.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_order_confirmation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyIdPicture',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_image', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to=antivienas.database.models.user_id_upload_path)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_img',
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=9546),
        ),
    ]
