# Generated by Django 5.0.4 on 2024-11-23 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_order_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=5384),
        ),
        migrations.AlterField(
            model_name='verifyidpicture',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='idpicture', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
