# Generated by Django 5.0.4 on 2024-05-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_user_birthday_alter_user_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
    ]
