# Generated by Django 5.0.4 on 2024-05-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_user_description_alter_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='friendsetting',
            name='account_holder_details',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendsetting',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
