# Generated by Django 5.0.4 on 2024-05-19 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_friendsetting_profit_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='order',
            name='meeting_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='meeting_hour',
            field=models.PositiveIntegerField(default=930),
            preserve_default=False,
        ),
    ]
