# Generated by Django 5.0.4 on 2024-05-19 12:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_alter_order_meeting_hour_alter_order_no_of_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meeting_day',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 20))]),
        ),
    ]
