# Generated by Django 5.0.4 on 2024-05-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
