# Generated by Django 5.0.4 on 2024-05-19 19:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_alter_order_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meeting_day',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 18))]),
        ),
    ]
