# Generated by Django 5.0.4 on 2024-05-19 19:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_alter_order_meeting_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='friend_comment',
            field=models.TextField(blank=True, default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispute',
            name='user_comment',
            field=models.TextField(blank=True, default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='meeting_day',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 19))]),
        ),
    ]
