# Generated by Django 5.0.4 on 2024-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_alter_order_meeting_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_disputable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='friendsetting',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Naujokas'), (2, 'Patyręs'), (3, 'Ekspertas'), (4, 'Veteranas')], default=1),
        ),
    ]
