# Generated by Django 5.0.4 on 2024-10-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_order_is_disputable_alter_friendsetting_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=3081),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, 'Initiated'), (2, 'Confirmed'), (3, 'Paid'), (4, 'Complete'), (5, 'Cancelled'), (6, 'Abandoned'), (7, 'Disputed'), (8, 'Failed')], default=1),
        ),
    ]
