# Generated by Django 5.0.4 on 2024-10-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_order_confirmation_code_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsetting',
            name='description',
            field=models.CharField(blank=True, default='Sąryšis vienas su vienu...', max_length=130),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=2038),
        ),
    ]
