# Generated by Django 5.0.4 on 2024-10-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_friendsetting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsetting',
            name='description',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=9431),
        ),
    ]
