# Generated by Django 5.0.4 on 2024-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_alter_friendsetting_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsetting',
            name='description',
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.SmallIntegerField(default=5415),
        ),
    ]
